### ISSUE TITLE
Incorrect password issue

### ISSUE THREAD

**Issue by MrCyberlord** [arunkumar413/task-force#6]
![image](https://github.com/user-attachments/assets/ab644f9d-2de0-4ca7-a663-dfdab5f7d814)

@arunkumar413  I am getting this error while starting the backend! Any solution in mind ?

_Originally posted by @MrCyberlord in https://github.com/arunkumar413/task-force/issues/2#issuecomment-2437193207_

**Comment by arunkumar413** [comment]
@MrCyberlord You need to point the configuration in the file `server/DBConfig.js` to your local machine postgres DB username and password.

**Comment by MrCyberlord** [comment]
Got it! Your solution has solved the issue.

**Comment by MrCyberlord** [comment]
@arunkumar413  your solution has solved the issue.

**Comment by MrCyberlord** [comment]
Thanks
